### PR TITLE
Enhanced web page visuals.

### PR DESCRIPTION
**Pull request by NicBonetto**
screen shot 2017-06-20 at 11 37 59 am

### CODE REVIEW

**Comment by NicBonetto** [comment]
wave-overflow-demo

**Review by thebearingedge — CHANGES_REQUESTED** [review]
- [ ] Avoid black for... everything
- [ ] Box shadows should be _very_ subtle, use the alpha channel to make them transparent.
- [ ] Avoid borders when you can, else make them very subtle.
- [ ] Pick a color scheme and use the desaturated versions of those colors for your "dark" colors.
- [ ] Try [Paletton](http://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF)

**Comment by NicBonetto** [comment]
screen shot 2017-06-20 at 2 06 26 pm

**Comment by NicBonetto** [comment]
screen shot 2017-06-20 at 2 18 26 pm

**Pull request closed without merging**
